---
name: RPICT MQTT
version: prod
slug: rpict-mqtt
description: Send RPICT values to MQTT .
url: https://github.com/cyrilgt/ha-rpict-mqtt-addon
codenotary: cyril.guironnet@deckad.fr
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
legacy: true
uart: true
gpio: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/ttyAMA0
environment:
  MQTT_URL: "mqtt://127.0.0.1:1883"
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  MQTT_BASE_TOPIC: "rpict"
  ABSOLUTE_VALUES: "false"
  SENSOR_VALUE_THRESHOLD: "2"
options:
  MQTT_URL: "mqtt://127.0.0.1:1883"
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  MQTT_BASE_TOPIC: "rpict"
  ABSOLUTE_VALUES: "false"
  SENSOR_VALUE_THRESHOLD: "2"
schema:
  MQTT_URL: "str"
  MQTT_USER: "str"
  MQTT_PASSWORD: "str"
  MQTT_BASE_TOPIC: "str"
  ABSOLUTE_VALUES: "str"
  SENSOR_VALUE_THRESHOLD: "str"
